export const LOAD_SESSION_SUCCESS = 'LOAD_SESSION_SUCCESS'
export const LOAD_SESSION_PARSE_SUCCESS = 'LOAD_SESSION_PARSE_SUCCESS'
export const REMOVE_SESSION = 'REMOVE_SESSION'

export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'

//users TODO smooth out create user functionality in app
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC'
export const SELECT_GROUP = 'SELECT_GROUP'
export const CLEAR_USERS = "CLEAR_USERS"

//bank accounts
export const LOAD_BANK_ACCOUNTS_SUCCESS = 'LOAD_BANK_ACCOUNTS_SUCCESS'
export const CREATE_BANK_ACCOUNT_SUCCESS = 'CREATE_BANK_ACCOUNT_SUCCESS'
export const DELETE_BANK_ACCOUNT_SUCCESS = 'DELETE BANK ACCONT_SUCCESS'
export const CLEAR_BANK_ACCOUNTS = "CLEAR_BANK_ACCOUNTS"

//roles
export const ADD_USER_ROLE_SUCCESS = "ADD_USER_ROLE_SUCCESS"
export const REMOVE_USER_ROLE_SUCCESS = "REMOVE_USER_ROLE_SUCCESS"
export const LOAD_ALL_ROLES_SUCCESS = 'LOAD_ALL_ROLES_SUCCESS'
export const LOAD_USERS_FOR_ROLE_SUCCESS = 'LOAD_USERS_FOR_ROLE_SUCCESS'
export const CHANGE_GROUP_ROLE_SUCCESS = 'CHANGE_GROUP_ROLE_SUCCESS'
export const CLEAR_ROLES = 'CLEAR_ROLES'

//game nights
export const LOAD_ALL_GAME_NIGHTS_SUCCESS = "LOAD_ALL_GAME_NIGHTS_SUCCESS"
export const LOAD_ALL_GAME_NIGHT_VOTES_SUCCESS = "LOAD_ALL_GAME_NIGHT_VOTES_SUCCESS"
export const CREATE_GAME_NIGHT_SUCCESS = "CREATE_GAME_NIGHT_SUCCESS"
export const UPDATE_GAME_NIGHT_SUCCESS = "UPDATE_GAME_NIGHT_SUCCESS"
export const CLEAR_GAME_NIGHT = "CLEAR_GAME_NIGHT"

//prints
export const LOAD_ALL_PRINTS_SUCCESS = "LOAD_ALL_PRINTS_SUCCESS"
export const CREATE_PRINT_SUCCESS = "CREATE_PRINT_SUCCESS"
export const UPDATE_PRINT_SUCCESS = "UPDATE_PRINT_SUCCESS"
export const DELETE_PRINT_OPTIMISTIC = "DELETE_PRINT_OPTIMISTIC"

//schedule
export const LOAD_ALL_SCHEDULES_SUCCESS = "LOAD_ALL_SCHEDULES_SUCCESS"
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS"
export const DELETE_SCHEDULE_OPTIMISTIC = "DELETE_SCHEDULE_OPTIMISTIC"
